version: '2'

networks: 
  credentials:

services: 

  ca_admin:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.admin.credentials.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports: 
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/admin:/etc/hyperledger/fabric-ca-server
    container_name: ca.admin.credentials.com
    hostname: ca.admin.credentials.com
    networks: 
      - credentials

  ca_user:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.user.credentials.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports: 
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/user:/etc/hyperledger/fabric-ca-server
    container_name: ca.user.credentials.com
    hostname: ca.user.credentials.com
    networks: 
      - credentials

  ca_orderer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports: 
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks: 
      - credentials