version: '2'

volumes: 
  orderer.credentials.com:
  orderer2.credentials.com:
  orderer3.credentials.com:
  peer0.admin.credentials.com:
  peer1.admin.credentials.com:
  peer0.user.credentials.com:
  peer1.user.credentials.com:


networks: 
  credentials:

services: 

# ORDERERS
  orderer.credentials.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: orderer.credentials.com
    container_name: orderer.credentials.com
    networks: 
      - credentials

  orderer2.credentials.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: orderer2.credentials.com
    container_name: orderer2.credentials.com
    networks: 
      - credentials

  orderer3.credentials.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: orderer3.credentials.com
    container_name: orderer3.credentials.com
    networks: 
      - credentials

# PEERS
  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - credentials

  peer0.admin.credentials.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer0.admin.credentials.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
    depends_on:
      - couchdb1
    networks: 
      - credentials
  
  couchdb2:
    container_name: couchdb2
    image: couchdb:3.1.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    networks:
      - credentials

  peer1.admin.credentials.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer1.admin.credentials.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
    depends_on:
      - couchdb2
    networks: 
      - credentials

  couchdb3:
    container_name: couchdb3
    image: couchdb:3.1.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7984:5984
    networks:
      - credentials

  peer0.user.credentials.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer0.user.credentials.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
    depends_on:
      - couchdb3
    networks: 
      - credentials

  couchdb4:
    container_name: couchdb4
    image: couchdb:3.1.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 8984:5984
    networks:
      - credentials

  peer1.user.credentials.com:
    extends: 
      file: base/docker-compose-base.yaml
      service: peer1.user.credentials.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
    depends_on:
      - couchdb4
    networks: 
      - credentials



